<?php

namespace AppBundle\Repository;

use AppBundle\Entity\User;
use AppBundle\Entity\UserToken;

/**
 * UserTokenRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserTokenRepository extends \Doctrine\ORM\EntityRepository
{
    public function createTokenForUser(User $u) : UserToken
    {
        $token_len = 64;
        $t = bin2hex(random_bytes($token_len));

        $token = new UserToken();
        $token->setEmail($u->getEmail());
        $token->setToken($t);

        $em = $this->getEntityManager();
        $em->persist($token);
        $em->flush();

        return $token;
    }

    public function createUserAndToken(User $u) : UserToken
    {
        $em = $this->getEntityManager();
        $em->persist($u);
        $em->flush();

        $token = $this->createTokenForUser($u);

        return $token;
    }

    public function getToken(String $token) : UserToken
    {
        $date = new \DateTime();
        date_sub($date, date_interval_create_from_date_string('20 minutes'));

        $r = $this->createQueryBuilder('t')
                    ->andWhere('t.created_at > :date')
                    ->setParameter('date', $date)
                    ->getQuery()
                    ->execute();

        return $r != null ? $r[0] : null;
    }
}
