<?php

namespace AppBundle\Repository;

use AppBundle\Entity\User;

/**
 * YearsPaidRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class YearsPaidRepository extends \Doctrine\ORM\EntityRepository
{
    public function shouldPay(User $user) : Boolean
    {
        $y = date('Y');
        $em = $this->getDoctrine()->getManager();
        $years = $this->findBy([
            'user' => $user->getEmail(),
        ]);

        for ($i = 0; $i < count($years); $i++) {
            if ($years[$i]->getYear() == $y) {
                return false;
            }
        }

        return true;
    }
}
